### ISSUE TITLE
`Please install ip.`  WTF?[BUG]

### ISSUE THREAD

**Issue by anoduck** [Rafficer/linux-cli-community#366]
**Describe the bug**
Installed with sudo without a hitch, most of the requirements were already installed. Went to initialize the service and received the following error message.

``` sh
'ip' not found.
Please install ip.
```

**To Reproduce**
1. Begin with a fresh install of OpenBSD Current/Snapshot with Python installed.
2. Install the necessary dependencies: `doas pkg_add -U openvpn dialog`
3. Assuming you are not root. Enter the following command at the prompt. `doas pip3 install -U protonvpn-cli` If you are logged in as root, omit the 'doas'.
4. Run `doas protonvpn init`
5. See error

**Expected behavior**
From the required dependencies, no problem was expected to occur. So the rather obscure error message is quite surprising.

**Error Messages/Program Output/Log Messages (~/.pvpn-cli/pvpn-cli.log)**
``` sh
'ip' not found. 
Please install ip.
```
pvpn-cli-log
``` sh
2024-03-15 04:23:00,027 — protonvpn-cli — DEBUG — cli:89 — ###########################
2024-03-15 04:23:00,028 — protonvpn-cli — DEBUG — cli:90 — ### NEW PROCESS STARTED ###
2024-03-15 04:23:00,028 — protonvpn-cli — DEBUG — cli:91 — ###########################
2024-03-15 04:23:00,028 — protonvpn-cli — DEBUG — cli:92 — ['/usr/local/bin/protonvpn', 'init']
2024-03-15 04:23:00,028 — protonvpn-cli — DEBUG — cli:93 — USER: User
2024-03-15 04:23:00,029 — protonvpn-cli — DEBUG — cli:94 — CONFIG_DIR: /home/User/.pvpn-cli
2024-03-15 04:23:00,034 — protonvpn-cli — DEBUG — cli:97 — Arguments
{'--cc': None, '--fastest': False, '--help': False, '--p2p': False, '--random': False, '--sc': False, '--tor': False, '--version': False, '-p': None, '<servername>': None, 'c': False, 'configure': False, 'connect': False, 'd': False, 'disconnect': False, 'examples': False, 'init': True, 'r': False, 'reconnect': False, 'refresh': False, 's': False, 'status': False}
2024-03-15 04:23:00,045 — protonvpn-cli — DEBUG — check_root:347 — ip not found
```

**Desktop (please complete the following information):**
 - OS: OpenBSD Current
 - Python Version: 3.11.8
 - ProtonVPN-CLI Version: 2.2.11

**Additional context**

**Comment by anoduck** [comment]
Could this by any chance be referring to iptables? Just somehow the "tables" got cutoff?

**Comment by ErichRitz** [comment]
No, the program is in fact called "ip".

```
# which ip
/usr/sbin/ip
# file /usr/sbin/ip
/usr/sbin/ip: symbolic link to ../../sbin/ip
```

https://ipset.netfilter.org/ipset.man.html

**Comment by anoduck** [comment]
Then the error message should read `Please install iproute2` to avoid the misunderstanding. 

I do not know if every Linux distribution has adopted the use of iproute2 as their recommended means to configure network interfaces. There are so many different Linux distributions, it is quite possible no one knows. 

Regardless, it rules out any possibility of being compatible with BSD.
